version: "3"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: my_proj
    volumes:
      - .:/my_proj
    ports:
      - "8000:8000"