version: "3"

services:
  web:
    image: my_proj
    command: gunicorn psd.wsgi:application -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
      - ./psd/static:/app/psd/static
    expose:
      - "8000"
